[package]
name = "Memento Mori"
authors = ["Kalinter, globemallow, JosephMcKean, ProfArmitage"]
version = "1.2.6"

[dependencies.mods."Tamriel_Data"]
plugin = "Tamriel_Data.esm"

[dependencies.mods."OAAB_Data"]
plugin = "OAAB_Data.esm"